// <auto-generated />
using System;
using Kokosoft.SimmingPoolTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Kokosoft.SimmingPoolTracker.API.Migrations
{
    [DbContext(typeof(PoolScheduleContext))]
    [Migration("20190225110933_SwimmingPools")]
    partial class SwimmingPools
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Kokosoft.SwimmingPoolTracker.ImportSchedule.Model.Pool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("ShortName");

                    b.HasKey("Id");

                    b.ToTable("SwimmingPools");
                });

            modelBuilder.Entity("Kokosoft.SwimmingPoolTracker.ImportSchedule.Model.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Day");

                    b.Property<int?>("PoolId");

                    b.Property<string>("Time");

                    b.Property<int>("Track25");

                    b.Property<int>("Track50");

                    b.Property<int>("TrackShallow");

                    b.HasKey("Id");

                    b.HasIndex("PoolId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Kokosoft.SwimmingPoolTracker.ImportSchedule.Model.Schedule", b =>
                {
                    b.HasOne("Kokosoft.SwimmingPoolTracker.ImportSchedule.Model.Pool", "Pool")
                        .WithMany()
                        .HasForeignKey("PoolId");
                });
#pragma warning restore 612, 618
        }
    }
}
